### PR TITLE
Add compile dir to repo

### PR DESCRIPTION
**Pull request by antonvas**
We need this to use latest js/css on gh-page

### CODE REVIEW

**Comment by osavchenko** [comment]
I suggest also add minified versions

**Comment by BernardoSilva** [comment]
would be awesome to have the minified version as well. can you have a look into that @antonvas ? :)

**Comment by antonvas** [comment]
Sure added @BernardoSilva @osavchenko

**Comment by osavchenko** [comment]
Cool! :+1:

**Comment by amyboyd** [comment]
Isn't there a way to compile when deploying to gh-pages? Source code control like git is for source code, not compiled code.

**Comment by antonvas** [comment]
@amyboyd It is better to speak to @BernardoSilva about this. As for me better to have compiled dir there. Because I can insert direct link to js/css in gh-page.

**Comment by hetmansky** [comment]
ok for me +1

**Comment by BernardoSilva** [comment]
@amyboyd it makes a lot easier to have the compiled library files available under version control to allow direct linking.
Latter on we can evolve this process, but is not critical and it does not have any downside having it under version control for now.

Also if someone wants to try this lib without having to download they can use this links like @antonvas is using for Gh-pages

**Pull request merged**
