### PR TITLE
Update editor icons

### PR DESCRIPTION
**Pull request by antonvas**
Used base64 encoded image and updated styles for buttons to make it looks pretty on dark background: http://screencast.com/t/jcVIi2tssNo

### CODE REVIEW

**Comment by antonvas** [comment]
retest this please

**Comment by amyboyd** [comment]
+1 - even better would be to use sprites or 2x PNG, so the icons look nice on retina devices. @sallymaeduke Do you have these?

**Comment by antonvas** [comment]
Ideal solution will be using custom font for those icons. (maybe just insert those to pm-font). But it is future improvements I think

**Comment by sallymaeduke** [comment]
I can add them to our custom font. It's up to you guys if you want to wait for me to do this, or add as an improvement in a seperate ticket.

**Comment by antonvas** [comment]
I'm voiting for next improvement. Added https://github.com/partnermarketing/pm-image-editor/issues/15.

Because currently I'm working on adding this editor to edit templates page.

**Comment by BernardoSilva** [comment]
If we want to add the icons to a font needs to be a separate font to be on this repository.
This library needs to be independent, so it needs to have the icons "locally".
I think is fine for now, but the 2x suggestion is a good one @amyboyd :+1:

**Comment by amyboyd** [comment]
OK to merge IMO.

Changing to SVG might be a bit too much for right now, but 2x PNGs should be just changing the file. If we have the 2x PNGs then we should do that change soon.

**Pull request merged**
